// 더미 파일들
export const getAssistantWorkspacesByWorkspaceId = async () => []
export const getChatsByWorkspaceId = async () => []
export const getCollectionWorkspacesByWorkspaceId = async () => []
export const getFileWorkspacesByWorkspaceId = async () => []
export const getFoldersByWorkspaceId = async () => []
export const getModelWorkspacesByWorkspaceId = async () => []
export const getPresetWorkspacesByWorkspaceId = async () => []
export const getPromptWorkspacesByWorkspaceId = async () => []
export const getToolWorkspacesByWorkspaceId = async () => []
export const getAssistantImageFromStorage = async () => null
export const getAssistantCollectionsByAssistantId = async () => []
export const getAssistantFilesByAssistantId = async () => []
export const getAssistantToolsByAssistantId = async () => []
export const updateChat = async () => null
export const getCollectionFilesByCollectionId = async () => []
export const deleteMessagesIncludingAndAfter = async () => null
export const getChatFilesByChatId = async () => []
export const getChatById = async () => null
export const getMessageFileItemsByMessageId = async () => []
export const getMessagesByChatId = async () => []
export const getMessageImageFromStorage = async () => null
export const createChatFiles = async () => null
export const createChat = async () => null
export const createMessageFileItems = async () => null
export const createMessages = async () => null
export const updateMessage = async () => null
export const uploadMessageImage = async () => null
export const getFileFromStorage = async () => null
export const createAssistants = async () => null
export const createChats = async () => null
export const createCollections = async () => null
export const createFiles = async () => null
export const createPresets = async () => null
export const createPrompts = async () => null
export const createTools = async () => null
export const createDocXFile = async () => null
export const createFile = async () => null
export const getProfileImageUrl = async () => null
export const uploadProfileImage = async () => null
export const getWorkspaceImageFromStorage = async () => null
export const getLimitsByUserId = async () => null
export const incrementProfileUsage = async () => null
export const resetProfileUsage = async () => null
